### ISSUE TITLE
Support for monorepos

### ISSUE THREAD

**Issue by pranshuchittora** [orta/danger-plugin-yarn#36]
Any way to use this for packages inside monorepos.

**Comment by orta** [comment]
Not today, either wrap up https://github.com/orta/danger-plugin-yarn/pull/18 or you can add support yourself 👍🏻

**Comment by fbartho** [comment]
@pranshuchittora `danger-plugin-yarn` works for monorepos today!

 @orta recently shipped #44 which makes `danger-plugin-yarn` better handle the case of multiple package.json files which were leading to duplicate install messages.
 
_Note: there's a minor typo (a trailing '}') that was fixed in #45 but hasn't shipped yet_

**Comment by glensc** [comment]
The ship:
- https://github.com/orta/danger-plugin-yarn/pull/45#issuecomment-999068357

was done incorrectly:
- https://github.com/orta/danger-plugin-yarn/issues/48

so, this can be closed once shipped properly.

**Comment by user512** [comment]
Looks like both issue #45 and #48 is 👍 in 1.5.1, should we close this issue?

**Comment by orta** [comment]
Seems reasonable to me
